"""
Script:         cli_command_interface.py
Author:         AutoForge Team

Description:
    core abstract base class which provides a standardized interface for implementing modular,
    pluggable command-line commands within the AutoForge framework.

    Each command subclass is responsible for:
        - Declaring its name and description.
        - Registering its CLI arguments using `argparse`.
        - Implementing execution logic based on parsed arguments.

    The interface supports both programmatic and shell-style invocation, enabling dynamic discovery
    and execution of commands across tools and environments.
"""

import argparse
import inspect
import io
import shlex
import sys
import time
from abc import ABC, abstractmethod
from typing import IO, Any, Optional

# AutoForge imports
from auto_forge import AutoForgeModuleType, AutoLogger, ModuleInfoType
from auto_forge.common.registry import Registry  # Runtime import to prevent circular import
from auto_forge.common.toolbox import ToolBox


class _CLICapturingArgumentParser(argparse.ArgumentParser):
    """
    A custom ArgumentParser that captures error messages into an internal string buffer
    instead of printing to stderr and exiting immediately.e.
    """

    def __init__(self, *args, **kwargs):
        """
        Initializes the parser and sets up an internal buffer to capture error messages.
        Args and kwargs are passed directly to the base ArgumentParser constructor.
        """
        self._toolbox = ToolBox.get_instance()
        self.error_output = io.StringIO()
        super().__init__(*args, **kwargs)

    def exit(self, status=0, message=None):
        """
        Overrides the default exit behavior to capture the message instead of printing.
        Args:
            status (int): Exit code to raise with SystemExit.
            message (str): Optional error message to capture.
        """
        if message:
            self.error_output.write(message.strip())
        raise SystemExit(status)

    def error(self, message):
        """
        Overrides the default error handling to capture the usage message and error text.
        Args:
            message (str): The error message generated by argparse.
        """
        self.print_usage(self.error_output)
        print(f"Error: {message.strip().capitalize()}")

        raise SystemExit(2)

    def get_error_message(self) -> str:
        """
        Returns the captured error message as a trimmed string.
        Returns:
            str: The accumulated error output from the most recent parse attempt.
        """
        return self.error_output.getvalue().strip()

    def print_help(self, _file: Optional[IO[str]] = None) -> None:
        """
        Overrides default help output with a custom help message.
        """
        help_text = self.format_help()

        lines = help_text.splitlines()
        output_lines = []

        skipping_usage = False

        for line in lines:
            stripped_line = line.lstrip()

            if not skipping_usage:
                if stripped_line.startswith("usage:"):
                    skipping_usage = True
                    continue  # Skip the 'usage:' line
                else:
                    output_lines.append(line)
            else:
                # We're in usage-skipping mode
                if stripped_line and not line.startswith(' '):
                    # A non-indented line => stop skipping
                    skipping_usage = False
                    output_lines.append(line)

        # Custom help before 'optional arguments:'
        custom_note = f"Args:\n  Run '{self.prog} --help' to see all available arguments\n"
        final_lines = []
        inserted = False

        for line in output_lines:
            if not inserted and line.strip().lower() == "optional arguments:":
                final_lines.append(custom_note)
                inserted = True
            final_lines.append(line)

        if not inserted:
            final_lines.append(custom_note)

        # 'argparse' essential minor touch-ups
        final_help = "\n".join(final_lines)
        final_help = final_help.replace("optional arguments:", "Optional Arguments:")
        final_help = final_help.replace("show this help message and exit", "Show this help message and exit.")

        print('\n' + final_help + '\n')

    def print_usage(self, _file: Optional[IO[str]] = None) -> None:
        """
        Overrides usage banner output.
        """
        self.print_help()


class CLICommandInterface(ABC):
    """
    Abstract base class for CLI commands that can be dynamically registered and executed.
    Each derived class must define its name, description, argument parser, and run logic.
    """

    # Error constants
    COMMAND_ERROR_NO_ARGUMENTS: int = 0xFFFF

    def __init__(self, command_name: Optional[str] = None,
                 raise_exceptions: Optional[bool] = False,
                 hidden: Optional[bool] = False):
        """
        Initializes the CLICommand and prepares its argument parser using
        the name and description provided by the subclass.
        Args:.
            command_name (str, optional): The name of the command.
            raise_exceptions (bool, optional): Whether to raise an exception when parsing errors.
            hidden (bool, optional): Whether to hide commands from the menu.
        """

        self._last_error: Optional[str] = None
        self._last_exception: Optional[Exception] = None
        self._raise_exceptions = raise_exceptions if raise_exceptions else False
        self._hidden = hidden if hidden else False
        self._command_name: str = command_name

        caller_frame = inspect.stack()[1].frame
        caller_globals = caller_frame.f_globals

        caller_module_name = caller_globals.get("AUTO_FORGE_MODULE_NAME", None)
        caller_module_description = caller_globals.get("AUTO_FORGE_MODULE_DESCRIPTION", "Description not provided")
        caller_module_version = caller_globals.get("AUTO_FORGE_MODULE_VERSION", "0.0.0")

        self._command_name: str = command_name if command_name is not None else caller_module_name
        # Create a command dedicated logger instance
        self._logger = AutoLogger().get_logger(name=command_name)

        # Persist this module instance in the global registry for centralized access
        registry = Registry.get_instance()
        self._module_info: ModuleInfoType = (
            registry.register_module(name=command_name,
                                     description=caller_module_description,
                                     version=caller_module_version,
                                     auto_forge_module_type=AutoForgeModuleType.CLI_COMMAND,
                                     hidden=self._hidden))

        # Optional tool initialization logic
        if not self.initialize() and self._raise_exceptions:
            raise RuntimeError(f"failed to initialize '{self._module_info.name}' command.")

        super().__init__()

    def get_last_error(self) -> Optional[str]:
        """
        Returns the last recorded error message, if an error occurred during the previous execution.
        Returns:
            Optional[str]: The error message string, or None if no error was recorded.
        """
        return self._last_error

    def get_info(self) -> ModuleInfoType:
        """
        Retrievers information about the implemented command line tool.
        Returns:
            ModuleInfoType: a named tuple containing the implemented command id
        """
        if self._module_info is None:
            raise RuntimeError('command info not initialized, make sure call set_info() first')

        return self._module_info

    def update_info(self, command_info: ModuleInfoType):
        """
        Updates information about the implemented command line tool.
        """
        self._module_info = command_info

    def execute(self, flat_args: Optional[str] = None, **kwargs: Any) -> Optional[int]:
        """
        Executes the command using either a shell-style string or structured kwargs.

        Args:
            flat_args (Optional[str]): If provided, a raw shell-style string (e.g., "--flag -v").
            **kwargs: Alternatively, keyword-style argument values (e.g., flag=True, count=3).

        Returns:
            int: 0 on success, non-zero on failure (e.g., usage error).
        """
        # Invalidate last error
        self._last_error = None
        return_value: int = 1

        # Call the mandatory implementation create_parser() to create parser instance if it's not created
        parser: _CLICapturingArgumentParser = _CLICapturingArgumentParser(
            prog=self._module_info.name,
            description=self._module_info.description
        )
        self.create_parser(parser)

        # Make sure we always support version
        parser.add_argument("-v", "--version", action="store_true", help="Show version and exit.")

        if flat_args is not None:
            args_list = shlex.split(flat_args.strip())
        else:
            args_list = []
            for key, value in kwargs.items():
                cli_key = f'--{key.replace("_", "-")}'
                if isinstance(value, bool):
                    if value:
                        args_list.append(cli_key)
                else:
                    args_list.extend([cli_key, str(value)])
        try:
            # Handle arguments special care for version output
            if "-v" in args_list or "--version" in args_list:
                print(f"AutoForge '{self._module_info.name}' version {self._module_info.version}")
                return_value = 0
            else:
                args = parser.parse_args(args_list)
                return_value = self.run(args)

            # Auto print help when no arguments provided
            if return_value == self.COMMAND_ERROR_NO_ARGUMENTS:
                parser.print_help()


        except SystemExit:

            self._last_error = parser.get_error_message()
            self._last_exception = None
        except Exception as execution_exception:
            self._last_error = str(execution_exception).strip()
            self._last_exception = execution_exception
        finally:
            time.sleep(0.1)
            if self._last_error is not None:
                if self._raise_exceptions:
                    if self._last_exception:
                        raise RuntimeError(self._last_error) from self._last_exception
                    else:
                        raise RuntimeError(self._last_error)
                else:
                    print(self._last_error)
            sys.stdout.flush()
        return return_value

    # noinspection PyMethodMayBeStatic
    def initialize(self, **_kwargs: Any) -> bool:
        """
        Optional interface method for command-specific one-time initialization.
        Args:
            **_kwargs (Any): Optional initialization parameters specific to the command.
        Returns:
            bool: True if initialization succeeded, False otherwise.
        """
        return True

    @abstractmethod
    def create_parser(self, parser: argparse.ArgumentParser) -> None:
        """
        Adds command-specific arguments to the provided parser.
        Args:
            parser (argparse.ArgumentParser): Parser to populate with arguments.
        """
        raise NotImplementedError("must implement 'create_parser'")

    @abstractmethod
    def run(self, args: argparse.Namespace) -> int:
        """
        Executes the actual logic of the command after parsing.
        Args:
            args (argparse.Namespace): Parsed arguments.
        Returns:
            int: 0 on success, non-zero on failure.
        """
        raise NotImplementedError("must implement 'run'")
